pub mod expression;
pub mod statement;

use crate::parser::expression::Expression;
use crate::lexer::tokens::Token;

use crate::Result;
use std::iter::Peekable;
use std::vec::IntoIter;
use crate::parser::statement::Statement;

/// [`Token`] Iterator type generated by the [`Lexer`].
///
/// [`Token`]: crate::lexer::tokens::Token
/// [`Lexer`]: crate::lexer::Lexer
type TokenIter = Peekable<IntoIter<Token>>;

/// An RDP (Recursive Descent Parser) which generates an AST (Abstract Syntax Tree)
pub struct Parser {
    /// [`Token`] Iterator generated by the [`Lexer`].
    ///
    /// [`Token`]: crate::lexer::tokens::Token
    /// [`Lexer`]: crate::lexer::Lexer
    pub tokens: TokenIter,
}

impl Parser {
    pub fn new(tokens: TokenIter) -> Self {
        Parser {
            tokens,
        }
    }

    pub fn parse(&mut self) -> Result<Statement> {
        self.parse_statement()
    }
}



